trigger:
- main

pool:
  name: Default

variables:
  sourceFolder: '$(Build.SourcesDirectory)'
  artifactFolder: '$(Build.ArtifactStagingDirectory)'
  packagesFolder: '$(Build.SourcesDirectory)\packages'

steps:
# Install NuGet
- task: NuGetToolInstaller@1

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(sourceFolder)\WCWebService.sln'
    feedsToUse: 'select'

- powershell: |
    $publish = "$(sourceFolder)\bin\release\publish"
    if (Test-Path $publish) { Remove-Item $publish -Recurse -Force }
  displayName: 'Clean publish folder to avoid nested web.config'


# Precompile Web Site (only once, correct path)
- powershell: |
    $output = "$(artifactFolder)\PrecompiledWeb"
    if (-not (Test-Path $output)) { New-Item -ItemType Directory -Path $output }
    & "$env:windir\Microsoft.NET\Framework64\v4.0.30319\aspnet_compiler.exe" `
        -v / `
        -p "$(sourceFolder)" `
        -u `
        -f $output
  displayName: 'Precompile Web Site'

# Archive precompiled site
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(artifactFolder)\PrecompiledWeb'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(artifactFolder)\WCWebService.zip'

# Publish artifact so it can be deployed
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(artifactFolder)\WCWebService.zip'
    artifact: 'drop'
    publishLocation: 'pipeline'