trigger:
- main

pool:
  name: Default

variables:
  solution: 'WCWebService.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packagesDir: '$(Build.SourcesDirectory)\packages'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    restoreSolution: 'WCWebService.sln'
    restoreDirectory: '$(packagesDir)'

- script: |
    echo "Copy missing DLLs to bin"
    mkdir "$(Build.SourcesDirectory)\bin"
    xcopy /Y /S "$(packagesDir)\**\*.dll" "$(Build.SourcesDirectory)\bin\"
  displayName: 'Copy NuGet DLLs to bin'

- task: VSBuild@1
  inputs:
    solution: 'WCWebService.sln'
    msbuildArgs: >
      /p:DeployOnBuild=true
      /p:WebPublishMethod=Package
      /p:PackageAsSingleFile=true
      /p:SkipInvalidConfigurations=true
      /p:PackageLocation="$(Build.ArtifactStagingDirectory)\WCWebService"
      /p:UseWPP_CopyWebApplication=true
      /p:AutoParameterizationWebConfigConnectionStrings=false
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
